spring.application.name=demo

spring.config.import=optional:classpath:application-secret.properties
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
app.featured-recipes.zone-id=UTC
